
# The Basics of NumPy Arrays 

## What is numpy?
---

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

---

<h1 align='center'> Basics</h1>

*  NumPy’s array class is called `ndarray`. It is also known by the alias `array`. Note that `numpy.array` is not the same as the Standard Python Library class `array.array`, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an `ndarray` object are:
    - `ndarray.ndim:` The number of axes(dimensions) of the array.
    - `ndarray.shape:` The dimension of array.For a matrix with x rows and y columns, shape will be (x,y).
    - `ndarray.size:` The total number of elements of the array or It is equal to the product of the elements of the `shape`.
    - `ndarray.dtype:` The type of the elements in the array. Additionally NumPy provides types of its own like- numpy.int32, numpy.int16, and numpy.float64.
    - `ndarray.itemsize:` The size in bytes of each element of the array. 
    - `ndarray.data:` The buffer containing the actual elements of the array. 

## Creating a NumPy array

In [1]:
import numpy as np

<font color='cadetblue' size='4'>Basic ndarray</font>


In [2]:
x=np.array([1, 2, 3, 4])
print(x.dtype)
print(x)

int32
[1 2 3 4]


In [3]:
# We can specify the type of data inside the array:
y=np.array([1,2,3,4], dtype=np.float32)
print(y.dtype)
print(y)

float32
[1. 2. 3. 4.]


<font size='4' font='italic'>Since NumPy arrays can contain only homogeneous datatypes, values will be upcast if the types do not match:</font>

In [4]:
np.array([1,2,3.0,4])

array([1., 2., 3., 4.])

**NumPy arrays can be multi-dimensional too.**

In [5]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

<font color='cadetblue' size='4'>Array of zeros</font>


In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<font color='cadetblue' size='4'>Array of Ones</font>


In [8]:
np.ones(5, dtype=np.int32)

array([1, 1, 1, 1, 1])

<font color='cadetblue' size='4'>Random number in array</font>

In [11]:
# random 
np.random.rand(2,3)

array([[0.90173106, 0.59997399, 0.00507187],
       [0.5350174 , 0.12289398, 0.37837426]])

In [12]:
np.random.randint(10, size=(2,3))

array([[3, 2, 3],
       [3, 0, 9]])

In [13]:
# An array of the choice
np.full((2,3), 3)

array([[3, 3, 3],
       [3, 3, 3]])

In [14]:
# empty
# creates an array whose initial content is random and depends on the state of the memory.
np.empty((2, 3)) 

array([[0.90173106, 0.59997399, 0.00507187],
       [0.5350174 , 0.12289398, 0.37837426]])

<font color='cadetblue' size='4'>Sequence of numbers</font>

To create sequences of numbers, `NumPy` provides the arange function which is analogous to the Python built-in range, but returns an array.



In [16]:
#[10, 30)
np.arange(10, 30, 3)

array([10, 13, 16, 19, 22, 25, 28])

In [17]:
np.arange(0, 2, 0.3)  # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

<font color='cadetblue' size='4'>Evenly spaced ndarray</font>

In [20]:
np.arange(10)#.reshape(2,5)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**Another similar function is `np.linspace()`, but instead of step size, it takes in the number of samples that need to be retrieved from the interval. A point to note here is that the last number is included in the values returned unlike in the case of `np.arange()`.**

In [22]:
#[0,1]
np.linspace(0,1,21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

<font color='cadetblue' size='4'>Identity Matrix in NumPy</font>

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**NumPy gives you the flexibility to change the diagonal along which the values have to be 1s. You can either move it above the main diagonal:**

In [24]:
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

**Or move it below the main diagonal**

In [25]:
np.eye(3, k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

<h1 align='center'>The Shape and Reshaping of NumPy Arrays</h1>

In [26]:
a = np.array([[5,10,15],[20,25,20]])
print('Array:','\n',a)
print('Dimension of the array:','\n',a.ndim)

Array: 
 [[ 5 10 15]
 [20 25 20]]
Dimension of the array: 
 2


In [27]:
a = np.arange(6).reshape(2,3)
print('Array:','\n',a)
print('Shape of the array:','\n',a.shape)
print('Number of rows = ',a.shape[0])
print('Number of columns = ',a.shape[1])
print('Size of array :',a.size)
print('Manual determination of size of array :',a.shape[0]*a.shape[1])

Array: 
 [[0 1 2]
 [3 4 5]]
Shape of the array: 
 (2, 3)
Number of rows =  2
Number of columns =  3
Size of array : 6
Manual determination of size of array : 6


<font color='cadetblue' size='4'>Reshaping a NumPy array</font>

In [28]:
# reshape
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

In [29]:
a = np.array([3,6,9,12,18,24, 44, 55, 66, 11, 22, 33])
print('Three rows :','\n',np.reshape(a,(3,-1)))
print('Three columns :','\n',np.reshape(a,(-1,3)))

Three rows : 
 [[ 3  6  9 12]
 [18 24 44 55]
 [66 11 22 33]]
Three columns : 
 [[ 3  6  9]
 [12 18 24]
 [44 55 66]
 [11 22 33]]


<font color='cadetblue' size='4'>Flattening a NumPy array</font>

In [30]:
a = np.ones((2,2))
b = a.flatten()
c = a.ravel()
print('Original shape :', a.shape)
print('Array :','\n', a)
print('Shape after flatten :',b.shape)
print('Array :','\n', b)
print('Shape after ravel :',c.shape)
print('Array :','\n', c)

Original shape : (2, 2)
Array : 
 [[1. 1.]
 [1. 1.]]
Shape after flatten : (4,)
Array : 
 [1. 1. 1. 1.]
Shape after ravel : (4,)
Array : 
 [1. 1. 1. 1.]


In [31]:
b[0] = 0
print(a)

[[1. 1.]
 [1. 1.]]


**In this case, the change made was not reflected in the original array.**

In [32]:
c[0] = 0
print(a)

[[0. 1.]
 [1. 1.]]


**But here, the changed value is also reflected in the original ndarray.**

What is happening here is that `flatten()` creates a ***Deep copy*** of the ndarray while `ravel()` creates a ***Shallow copy*** of the ndarray.

> Deep copy means that a completely new ndarray is created in memory and the ndarray object returned by flatten() is now pointing to this memory location. Therefore, any changes made here will not be reflected in the original ndarray.

> A Shallow copy, on the other hand, returns a reference to the original memory location. Meaning the object returned by ravel() is pointing to the same memory location as the original ndarray object. So, definitely, any changes made to this ndarray will also be reflected in the original ndarray too.

<h1 align='center'>Maths with NumPy arrays<h1>

In [33]:
data = np.array([1,2])
ones = np.ones(2, dtype=int)

In [34]:
#Addition
add = data+ones
print('Addition of two array','\n',add)

Addition of two array 
 [2 3]


In [36]:
#Subtraction:
sub = data - ones
print('Subraction of two array:','\n',sub)

#Multiplication:
multi = data*data
print('Multiplication of two array','\n',multi)

#Division:u
div = data/data
print('Division by a constant','\n',div)

Subraction of two array: 
 [0 1]
Multiplication of two array 
 [1 4]
Division by a constant 
 [1. 1.]


<font color='cadetblue' size='4'>Mean, Median and Standard deviation</font>

In [37]:
a = np.arange(5,15,2)
a

array([ 5,  7,  9, 11, 13])

In [38]:

print('Mean :',np.mean(a))
print('Standard deviation :',np.std(a))
print('Median :',np.median(a))

Mean : 9.0
Standard deviation : 2.8284271247461903
Median : 9.0


<font color='cadetblue' size='4'>Min-Max values and their indexes</font>

In [39]:
a = np.array([[1,6], [4,3]])
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.max(a,axis=1))

Min : [1 3]
Max : [6 4]


In [40]:
a = np.array([[1,6,5],
[4,3,7]])
# minimum along a column
print('Min :',np.argmin(a,axis=0))
# maximum along a row
print('Max :',np.argmax(a,axis=1))

Min : [0 1 0]
Max : [1 2]


<h1 align='center'>Sorting in NumPy arrays</h1>

In [41]:
a = np.array([1,4,2,5,3,6,8,7,9])
print('Sorted array:','\n',np.sort(a, kind='quicksort'))

b = np.array([[5,6,7,4],
              [9,2,3,7]])# sort along the column
print('Sort along column :','\n',np.sort(b, kind='mergresort',axis=1))
# sort along the row
print('Sort along row :','\n',np.sort(b, kind='mergresort',axis=0))

Sorted array: 
 [1 2 3 4 5 6 7 8 9]
Sort along column : 
 [[4 5 6 7]
 [2 3 7 9]]
Sort along row : 
 [[5 2 3 4]
 [9 6 7 7]]


<h1 align='center'>Indexing and Slicing of NumPy array</h1>

<font color='cadetblue' size='4'>Slicing 1-D NumPy arrays</font>

In [42]:
#initial position: included
#final position: excluded
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [43]:
print(a[1:5])

[2 3 4 5]


In [44]:
print(a[::2])

[1 3 5]


In [45]:
#3rd: step size
print(a[:6:2])
print(a[1::2])
print(a[1:6:])

[1 3 5]
[2 4 6]
[2 3 4 5 6]


<font color='cadetblue' size='4'>Slicing 2-D NumPy arrays</font>

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
# print first row values
print('First row values :','\n',a[0:1,:])
# with step-size for columns
print('Alternate values from first row:','\n',a[0:1,::2])
# 
print('Second column values :','\n',a[:,1::2])
print('Arbitrary values :','\n',a[0:1,1:3])

<h1 align='center'>Array Concatenation and Splitting</h1>

<font color='cadetblue' size='4'>Concatenation of arrays</font>

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument..

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

You can also concatenate more than two arrays at once:

In [ ]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
# concatenate along the first axis
np.concatenate([grid, grid])

In [ ]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

For working with arrays of mixed dimensions, it can be clearer to use the ``np.vstack`` (vertical stack) and ``np.hstack`` (horizontal stack) functions:

In [ ]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

In [ ]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

## References:

> https://numpy.org/doc/

> https://www.kaggle.com/learn/python